create new password screen for reset password flow (#62)
* Add html content to email with styling

* Install jsonwebtoken
 dependency

* Add JWT and html content to email

* Remove id from user model because it is in the default model.  This will be removed in a refactor

* Add jsonwebtoken dependency

* Add keys directory to gitignore

* Ajust foreign key in jwt model to resolve bug

* WIP in EmailUtils before refactor of logic to BE ResetPassword

* Comments resolved.  Small refactor to move jwt creation to JWTUtils file. Move resetPasswordEmail content to BE ResetPassword

* Move payload and token creation to within conditional that first checks for user in ResetPassword

* Remove console.logs

* Resolve comments

* Remove unused code and import from JWTUtils.ts.  Make secret generic for reusability

* Add route and FE component for finish-reset-password. Add BE endpoint for reset password to validate JWT token.

* Add type generics to useQuery for tokenValidationResponse.  Complete conditional rendering of reset password screen based on token validation

* Add .env.example file.  Remove default value for JWT_SECRET

* Provide generics to router.get and define type for params

* Fix type error for jwtSecret.  Check for undef

* Adjust casing of queryFunctionHelper in FinishResetPassword.tsx

* Add AbortController to queries

* Adjust styling on input, reduce bottom margin for FinishResetPassword

* Add findUserById helper function to Users.ts

* Add abort controller to query helper function and mutation in FinishResetPassword

* Add userEmail to backend API res /validate-token/:token

* Change variable name to tokenValidationResponse in FinishResetPassword

* Add const variable for userEmail from backend API res

* Add type generics to useQuery

* Add generics to queryFunctionHelper

* Clear console logs

* Add disabled email input to FinishResetPassword UI

* Add disabled email input to conditional rendering

* Add form width to w-64

* Add form width w-64:
git status

* Run pnpm run format

* Testing git hook

* Test Prettier, add line

* Correct import for build error TS2307: Cannot find module '../users/Users' or its corresponding type declarations

* Adjust ternary for conditional rendering for when token is not valid or expired

* Adjust styling of form when token is not valid or expired

* Change button text on reset password screen

* Self review.  Remove comments

* Remove absolute from button in reset password view

* Remove absolute from button in set new password view and adjust css to implement space between

* Change name of validate token endpoint to include api

* Adjust styling for password reset view

* Resolve comments

* Change a tag to link component

* Correct import

* Adjust tailwind config

Co-authored-by: Rhiannon Stanford <mochi@Rhiannons-iMac.local>