Create finish reset password endpoint (#61)
* Add html content to email with styling

* Install jsonwebtoken
 dependency

* Add JWT and html content to email

* Remove id from user model because it is in the default model.  This will be removed in a refactor

* Add jsonwebtoken dependency

* Add keys directory to gitignore

* Ajust foreign key in jwt model to resolve bug

* WIP in EmailUtils before refactor of logic to BE ResetPassword

* Comments resolved.  Small refactor to move jwt creation to JWTUtils file. Move resetPasswordEmail content to BE ResetPassword

* Move payload and token creation to within conditional that first checks for user in ResetPassword

* Remove console.logs

* Resolve comments

* Remove unused code and import from JWTUtils.ts.  Make secret generic for reusability

* Add route and FE component for finish-reset-password. Add BE endpoint for reset password to validate JWT token.

* Add .env.example file.  Remove default value for JWT_SECRET

* Provide generics to router.get and define type for params

* Fix type error for jwtSecret.  Check for undef

* Adjust casing of queryFunctionHelper in FinishResetPassword.tsx

* Add AbortController to queries

* Adjust styling on input, reduce bottom margin for FinishResetPassword

* Add findUserById helper function to Users.ts

* Add abort controller to query helper function and mutation in FinishResetPassword

* Add userEmail to backend API res /validate-token/:token

* Change variable name to tokenValidationResponse in FinishResetPassword

* Add const variable for userEmail from backend API res

* Add type generics to useQuery

* Add generics to queryFunctionHelper

* Clear console logs

* Add disabled email input to FinishResetPassword UI

* Add form width to w-64

* Run pnpm run format

* Testing git hook

* Test Prettier, add line

* Correct import for build error TS2307: Cannot find module '../users/Users' or its corresponding type declarations

* Remove absolute from button in reset password view

* Define QueryParams and ResponseBody types for validate token API in ResetPassword

* Remove optional chaining and void type from validate token api

* Change to truthiness check of jwtSecret in tokenIsValid function

* Add conditional to flaxFetch call in FinishResetPassword that checks for token.  Resolve TS errors

Co-authored-by: Rhiannon Stanford <mochi@Rhiannons-iMac.local>